ipu6epmtl: ov08x40: Add configuration for CVS component
intel/ipu6-camera-hal pull request #143
Opened 2024-12-31 03:45 UTC by drhooray

- Add OV08X40 tuning file
- Add OV08X40 graph settings for CVS components
- Modified resolution to adapt to the sensor pad
- Add CSI port number

2024-12-31 05:26 UTC, hao-yao approved these changes

2024-12-31 05:28 UTC, hao-yao requested changes
Please don't change file mode of ov08x40-uf.xml.

2024-12-31 06:47 UTC, hao-yao approved these changes

2024-12-31 06:48 UTC, merged

2025-02-01 13:53 UTC, jwrdegoede commented
This merge-request  / commit 93d36726027566f4a60d245189df13 breaks the camera on Lenovo ThinkPad X1 carbon gen 12 models.

These laptops have a 'CJFME55' sensor module id,  so I think this may be related to this part of the change:

```
-        <supportedTuningConfig value="NORMAL,VIDEO,OV08X40_CJFME55_MTL,
-                                      STILL_CAPTURE,VIDEO,OV08X40_CJFME55_MTL"/>
+        <supportedTuningConfig value="NORMAL,VIDEO,OV08X40_BBG802N3_RG_MTL,
+                                     STILL_CAPTURE,VIDEO,OV08X40_BBG802N3_RG_MTL"/>
```

After this change I get the following output launching a gst pipeline with icamerasrc:

```
hans@x1:~$ gst-launch-1.0 icamerasrc buffer-count=7 ! video/x-raw,format=NV12,width=1280,height=720 ! videoconvert ! xvimagesink  
Setting pipeline to PAUSED ...
[02-01 14:52:56.811] CamHAL[INF] aiqb file name OV08X40_BBG802N3_RG_MTL.aiqb
[02-01 14:52:56.811] CamHAL[INF] aiqb file name OV08X40_BBG802N3_RG_MTL.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
[02-01 14:52:56.813] CamHAL[INF] aiqb file name AR0234_TGL_10bits.aiqb
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[02-01 14:52:56.965] CamHAL[ERR] Start: Device node /dev/video1 IOCTL VIDIOC_STREAMON error: Broken pipe
[02-01 14:52:56.965] CamHAL[ERR] Device:Generic stream on failed.
[02-01 14:52:56.965] CamHAL[ERR] Devices stream on failed:-38
[02-01 14:52:56.965] CamHAL[ERR] Start capture unit failed with ret:-38.
[02-01 14:52:56.965] CamHAL[ERR] Camera device starts failed.
[02-01 14:52:56.965] CamHAL[WAR] @stop: device not started
```

2025-02-17 03:34 UTC, hao-yao commented
Hi Hans @jwrdegoede , appreciate your help.

In this change we replaced configs for ov08x40 module 'CJFME55' by 'BBG802N3'. The most significant change is that sensor raw resolution changed from 1928x1208 to 3856x2176 (need driver [patch 1](https://github.com/intel/ipu6-drivers/blob/master/patch/v6.12/0008-media-ov08x40-Add-support-for-2-4-lanes-support-at-1.patch) and [patch 2](https://github.com/intel/ipu6-drivers/blob/master/patch/v6.12/0009-media-ov08x40-Fix-the-horizontal-flip-control.patch) for upstream ov08x40.c). This is for an ongoing Dell's new product, and @drhooray also validated this change works on legacy devices including Lenovo's.

We could have a better solution. However,
1. This change is on the deadline for Dell's milestone, so we don't have much time for developing.
2. Dell's product can only use 3856x2176 raw input, as the CV chip between sensor & IPU seems refuse to transfer data in other resolutions. (That's ridiculous! I guess the firmware of CV chip was doing this). Thankfully devices without such CV chip seems supports ov08x40 at 3856x2176 by HW & FW level according to our test results.
3. If libcamhal can get the sensor module name, we could make a change to let it load different configs according to the sensor module name. Sensor driver can get module name [like this](https://github.com/intel/ipu6-drivers/blob/3340c78946ed015d8a2e9713d816c5caa8d0881a/drivers/media/i2c/ov02c10.c#L1600), but in sensor driver there isn't suitable interface to let libcamhal query the name. The module itself has no NVM data either.